# Generated by Django 5.2.6 on 2025-10-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
