# Generated by Django 5.0.6 on 2025-11-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_invite_invited_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskattachment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskattachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
