# Generated by Django 5.0.6 on 2025-12-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_project_image_project_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
