# Generated by Django 5.0.6 on 2026-01-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
