# Generated by Django 5.0.6 on 2026-01-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_invite_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='status',
        ),
    ]
