# Generated by Django 6.0.1 on 2026-01-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_project_project_name_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
