# Generated by Django 6.0.1 on 2026-01-14 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_activitylog_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='timestamp',
        ),
    ]
