# Generated by Django 6.0.1 on 2026-01-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_remove_activitylog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
