# Generated by Django 6.0.1 on 2026-01-14 03:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_activitylog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
