# Generated by Django 6.0.1 on 2026-01-14 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_activitylog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='image',
        ),
    ]
