# Generated by Django 6.0.1 on 2026-02-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
