# Generated by Django 6.0.2 on 2026-03-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_remove_project_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invite',
            name='team_invite_token_1c8d32_idx',
        ),
        migrations.RemoveIndex(
            model_name='invite',
            name='team_invite_expires_53987f_idx',
        ),
    ]
