# Generated by Django 6.0.2 on 2026-03-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_remove_invite_team_invite_token_1c8d32_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='plain_token',
        ),
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
