# Generated by Django 6.0.2 on 2026-03-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_remove_invite_plain_token_alter_invite_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('project_restored', 'Project Restored'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_deleted', 'Task Deleted'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added')], max_length=50),
        ),
    ]
