# Generated by Django 6.0.2 on 2026-03-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_alter_activitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
