# Generated by Django 5.0.6 on 2026-01-07 16:33

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('khanban', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
