# Generated by Django 5.0.6 on 2025-12-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanban', '0002_alter_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.DecimalField(db_index=True, decimal_places=10, default=0, max_digits=20),
        ),
    ]
