# Generated by Django 6.0.2 on 2026-03-29 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanban', '0003_task_task_title_trgm_idx_task_task_desc_trgm_idx_and_more'),
        ('team', '0020_alter_activitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='task_desc_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_tags_trgm_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='khanban_tas_priorit_48660f_idx'),
        ),
    ]
