# Generated by Django 5.0.6 on 2025-12-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanban', '0004_offlinetaskupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlinetaskupdate',
            options={'ordering': ['timestamp'], 'verbose_name': 'Offline Task Update', 'verbose_name_plural': 'Offline Task Updates'},
        ),
    ]
