# Generated by Django 5.0.6 on 2025-12-03 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanban', '0005_alter_offlinetaskupdate_options'),
        ('team', '0003_remove_taskcomment_task_remove_taskattachment_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='offlinetaskupdate',
            index=models.Index(fields=['user', 'delivered'], name='khanban_off_user_id_640229_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinetaskupdate',
            index=models.Index(fields=['project', 'delivered'], name='khanban_off_project_0a2002_idx'),
        ),
    ]
