# Generated by Django 5.0.6 on 2025-12-03 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanban', '0006_offlinetaskupdate_khanban_off_user_id_640229_idx_and_more'),
        ('team', '0003_remove_taskcomment_task_remove_taskattachment_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlinetaskupdate',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='offlinetaskupdate',
            unique_together={('user', 'project', 'payload', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='offlinetaskupdate',
            index=models.Index(fields=['user', 'project', 'delivered'], name='khanban_off_user_id_be992f_idx'),
        ),
    ]
