# Generated by Django 6.0.1 on 2026-02-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('team', '0015_remove_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_user_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='team.project'),
        ),
    ]
