# Generated by Django 6.0.1 on 2026-02-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_last_active_user_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_active_user_project',
        ),
    ]
