# Generated by Django 6.0.1 on 2026-02-06 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_last_active_user_project'),
        ('team', '0017_remove_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_active_user', to='team.project'),
        ),
    ]
